# Generated by Django 5.2.14 on 2026-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='영문 제목')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='개봉연도')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, verbose_name='TMDB ID')),
                ('genres', models.CharField(blank=True, max_length=200, verbose_name='장르')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='감독')),
                ('cast', models.TextField(blank=True, verbose_name='출연진')),
                ('runtime', models.CharField(blank=True, max_length=20, verbose_name='런타임')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='언어')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='제작국')),
                ('ott', models.CharField(blank=True, max_length=200, verbose_name='OTT')),
                ('overview', models.TextField(blank=True, verbose_name='줄거리')),
                ('combined_reviews', models.TextField(blank=True, verbose_name='수집 리뷰')),
                ('llm_4pillar', models.TextField(blank=True, verbose_name='4-Pillar 설명')),
                ('tone', models.CharField(default='slate', max_length=20, verbose_name='포스터 톤')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '영화',
                'verbose_name_plural': '영화 목록',
                'ordering': ['title'],
            },
        ),
    ]
