# Generated by Django 5.2.14 on 2026-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True, verbose_name='감독'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.TextField(blank=True, verbose_name='영문 제목'),
        ),
    ]
