# Generated by Django 5.2.14 on 2026-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_sync_csv_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='context',
            field=models.CharField(blank=True, choices=[('', '미지정'), ('퇴근길·번아웃', '퇴근길·번아웃'), ('이별 직후', '이별 직후'), ('머리 비우고 싶을 때', '머리 비우고 싶을 때'), ('답답함을 뚫고 싶을 때', '답답함을 뚫고 싶을 때'), ('동기부여가 필요할 때', '동기부여가 필요할 때'), ('강렬함이 필요할 때', '강렬함이 필요할 때'), ('이별 후 회복기', '이별 후 회복기')], default='', max_length=100, verbose_name='추천 컨텍스트'),
        ),
        migrations.AddField(
            model_name='movie',
            name='load',
            field=models.CharField(blank=True, choices=[('', '미지정'), ('Low-Load', 'Low-Load'), ('Fast-paced', 'Fast-paced'), ('High-Load', 'High-Load')], default='', max_length=20, verbose_name='인지부하'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=200, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=10, verbose_name='언어'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview_ko',
            field=models.TextField(blank=True, verbose_name='한국어 줄거리'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='상영시간(분)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_ko',
            field=models.TextField(verbose_name='한국어 제목'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_original',
            field=models.TextField(blank=True, verbose_name='원어 제목'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(unique=True, verbose_name='TMDB ID'),
        ),
    ]
