# Generated by Django 5.2.14 on 2026-06-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_context_movie_load_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sensory',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='감각 태그 (쉼표 구분 다중값)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='context',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='추천 컨텍스트 (쉼표 구분 다중값)'),
        ),
    ]
